export default {
  accounts_info: null,
  acquirer_reconciliation: [],
  additional_info: {
    authentication_code: null,
    available_balance: null,
    nsu_processadora: null,
  },
  authorization_code: "229549003",
  binary_mode: false,
  brand_id: null,
  build_version: "3.27.0-rc-2",
  call_for_authorize_id: null,
  captured: true,
  card: {
    cardholder: { identification: [Object], name: "APRO" },
    date_created: "2023-11-22T18:54:09.000-04:00",
    date_last_updated: "2023-11-22T18:54:09.000-04:00",
    expiration_month: 11,
    expiration_year: 2025,
    first_six_digits: "503143",
    id: null,
    last_four_digits: "6351",
  },
  charges_details: [
    {
      accounts: [Object],
      amounts: [Object],
      client_id: 0,
      date_created: "2023-11-22T18:54:09.000-04:00",
      id: "1319680811-001",
      last_updated: "2023-11-22T18:54:09.000-04:00",
      metadata: {},
      name: "mercadopago_fee",
      refund_charges: [],
      reserve_id: null,
      type: "fee",
    },
  ],
  collector_id: 808086099,
  corporation_id: null,
  counter_currency: null,
  coupon_amount: 0,
  currency_id: "BRL",
  date_approved: "2023-11-22T18:54:09.291-04:00",
  date_created: "2023-11-22T18:54:09.048-04:00",
  date_last_updated: "2023-11-22T18:54:09.291-04:00",
  date_of_expiration: null,
  deduction_schema: null,
  description: null,
  differential_pricing_id: null,
  external_reference: null,
  fee_details: [
    { amount: 4.98, fee_payer: "collector", type: "mercadopago_fee" },
  ],
  financing_group: null,
  id: 1319680811,
  installments: 1,
  integrator_id: null,
  issuer_id: "24",
  live_mode: false,
  marketplace_owner: null,
  merchant_account_id: null,
  merchant_number: null,
  metadata: {},
  money_release_date: "2023-11-22T18:54:09.291-04:00",
  money_release_schema: null,
  money_release_status: "released",
  notification_url: null,
  operation_type: "regular_payment",
  order: {},
  payer: {
    identification: { number: "32659430", type: "DNI" },
    entity_type: null,
    phone: { number: null, extension: null, area_code: null },
    last_name: null,
    id: "1557192941",
    type: null,
    first_name: null,
    email: "test_user_80507629@testuser.com",
  },
  payment_method: {
    data: { routing_data: [Object] },
    id: "master",
    issuer_id: "24",
    type: "credit_card",
  },
  payment_method_id: "master",
  payment_type_id: "credit_card",
  platform_id: null,
  point_of_interaction: {
    business_info: { sub_unit: "sdk", unit: "online_payments" },
    type: "UNSPECIFIED",
  },
  pos_id: null,
  processing_mode: "aggregator",
  refunds: [],
  shipping_amount: 0,
  sponsor_id: null,
  statement_descriptor: null,
  status: "approved",
  status_detail: "accredited",
  store_id: null,
  tags: null,
  taxes_amount: 0,
  transaction_amount: 100,
  transaction_amount_refunded: 0,
  transaction_details: {
    acquirer_reference: null,
    external_resource_url: null,
    financial_institution: null,
    installment_amount: 100,
    net_received_amount: 95.02,
    overpaid_amount: 0,
    payable_deferral_period: null,
    payment_method_reference_id: null,
    total_paid_amount: 100,
  },
};
