export default [
  {
    name: "iBrat",
    url: require("../logos/iBrat.png"),
    insta: "ibratnacional",
    id: "iBrat",
    label: "logo iBrat",
  },
  {
    name: "TechT",
    url: require("../logos/techT.png"),
    insta: "techt_informatica",
    id: "techT",
    label: "logo techT",
  },
  {
    name: "Transguys",
    url: require("../logos/Transguys.png"),
    insta: "transguysbr",
    id: "Transguys",
    label: "Transguys",
  },
  {
    name: "Softview Tech",
    url: require("../logos/Softview.png"),
    insta: "softviewtech",
    id: "softviewtech",
    label: "Softview Tech",
  },
  {
    name: "Azuma Dojo",
    url: require("../logos/azuma.jpg"),
    insta: "azuma.dojo",
    id: "AzumaDojo",
    label: "Azuma Dojo",
  },
  {
    name: "Different Clinic",
    url: require("../logos/BeDifferent.png"),
    insta: "clinicdifferent",
    id: "BeDifferent",
    label: "logo BeDifferent",
  },
  {
    name: "Voz Da Diversidade",
    url: require("../logos/VozDaDiversidade.png"),
    insta: "vozdadiversidade",
    id: "VozDaDiversidade",
    label: "Voz Da Diversidade",
  },
  {
    name: "",
    url: require("../logos/MrRice.png"),
    insta: "mr.ricecream",
    id: "MrRice",
    label: "logo MrRice",
  },
  {
    name: "BeDifferent Clinic",
    url: require("../logos/BeDifferent.png"),
    insta: "clinicdifferent",
    id: "BeDifferent",
    label: "logo BeDifferent",
  },
  {
    name: "Vida Ativa",
    url: require("../logos/vidaativa.jpg"),
    insta: "vidaativa_ns",
    id: "vidaativa",
    label: "logo vidaativa",
  },
  {
    name: "Liga Trans",
    url: require("../logos/ligaTrans.png"),
    insta: "liganacionaldefutebol_linfat",
    id: "ligaTrans",
    label: "logo Liga Trans",
  },
];
